services:
  app:
    build: .
    image: plantilla:latest
    container_name: plantilla
    ports:
      - "3000:3000"
    volumes:
      # Monta el código fuente para hot reload
      - type: bind
        source: .
        target: /app
        consistency: cached
      # Excluye node_modules y .next para evitar conflictos
      - /app/node_modules
      - /app/.next
    environment:
      - NODE_ENV=development
      - WATCHPACK_POLLING=true
      - CHOKIDAR_USEPOLLING=true
      - CHOKIDAR_INTERVAL=1000
      - FORCE_COLOR=1
      - NEXT_TELEMETRY_DISABLED=1
    stdin_open: true
    tty: true
    command: pnpm dev --hostname 0.0.0.0 --port 3000

networks:
  default:
    name: plantilla-network
    driver: bridge
