services:
  db:
    image: mysql:8.0
    container_name: plantilla-db
    ports:
      - "3307:3306"
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: plantilla-db
      MYSQL_USER: user
      MYSQL_PASSWORD: password
    volumes:
      - mysql_data:/var/lib/mysql
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      timeout: 5s
      retries: 10

  app:
    build: .
    image: plantilla:latest
    container_name: plantilla
    ports:
      - "3000:3000"
    volumes:
      # Monta el código fuente para hot reload
      - type: bind
        source: .
        target: /app
        consistency: cached
      # Usa volúmenes nombrados para node_modules y .next
      - node_modules:/app/node_modules
      - next_cache:/app/.next
    env_file:
      - .env
    environment:
      - NODE_ENV=development
      - WATCHPACK_POLLING=true
      - CHOKIDAR_USEPOLLING=true
      - CHOKIDAR_INTERVAL=1000
      - FORCE_COLOR=1
      - NEXT_TELEMETRY_DISABLED=1
    depends_on:
      db:
        condition: service_healthy
    stdin_open: true
    tty: true
    command: pnpm dev --hostname 0.0.0.0 --port 3000

networks:
  default:
    name: plantilla-network
    driver: bridge

# Define los volúmenes persistentes
volumes:
  node_modules:
  next_cache:
  mysql_data:
